### ISSUE TITLE
get_os_version does not work with 16.1.01a systems

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm-Exchange/stackstorm-network_essentials#3]
Reported in #community, `get_os_version` does not work properly with systems running `16.1.01a`:

```
st2.actions.python.GetOsVersion: ERROR    Error while logging in to test-slx1.lab due to 16.1.1
Traceback (most recent call last):
  File "/opt/stackstorm/packs/network_essentials/actions/ne_base.py", line 834, in wrapper
    return func(*args, **kwds)
  File "/opt/stackstorm/packs/network_essentials/actions/get_os_version.py", line 38, in switch_operation
    with self.pmgr(conn=self.conn, auth=self.auth) as device:
  File "/opt/stackstorm/virtualenvs/network_essentials/lib/python2.7/site-packages/pyswitch/device.py", line 128, in __init__
    if nos_attr in os_table[ver]:
KeyError: '16.1.1'
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 155, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/network_essentials/actions/get_os_version.py", line 30, in run
    version = self.switch_operation(mgmt_ip)
  File "/opt/stackstorm/packs/network_essentials/actions/ne_base.py", line 834, in wrapper
    return func(*args, **kwds)
  File "/opt/stackstorm/packs/network_essentials/actions/get_os_version.py", line 38, in switch_operation
    with self.pmgr(conn=self.conn, auth=self.auth) as device:
  File "/opt/stackstorm/virtualenvs/network_essentials/lib/python2.7/site-packages/pyswitch/device.py", line 128, in __init__
    if nos_attr in os_table[ver]:
KeyError: '16.1.1'
```

These systems are running 16.1.01a. We list 16.1.1 as a supported version - is that meant to include 16.1.01a?

```
test-slx1# sh version

SLX-OS Operating System Software
SLX-OS Operating System Version: 16r.1.01
Copyright (c) 1995-2017 Brocade Communications Systems, Inc.
Firmware name:      16r.1.01a
Build Time:         01:44:40 Dec 22, 2016
Install Time:       07:23:14 Feb 27, 2017
Kernel:             2.6.34.6

Control Processor:  GenuineIntel with 7890 MB of memory

System Uptime:   0days 13hrs 8mins 31secs

Slot    Name    Primary/Secondary Versions                         Status
---------------------------------------------------------------------------
M1      SLX-OS  16r.1.01a                                          ACTIVE*
                16r.1.01a
L1/0    SLX-OS  16r.1.01a                                          ACTIVE
                16r.1.01a
L3/0    SLX-OS  16r.1.01a                                          ACTIVE
                16r.1.01a
```

**Comment by LindsayHill** [comment]
Addressed in newer pyswitchlib builds
